### PR TITLE
Upgrade Hawtio to version 1.4.52

### PR DESCRIPTION
**Pull request by oscerd**
Hi,

This PR upgrades Hawtio to version 1.4.52

Andrea

### CODE REVIEW

**Comment by davsclaus** [comment]
add to whitelist

@oscerd thanks a lot for all of this work, I learned about a whitelist, so I am adding you to that, so your PR should be auto merged if they pass now. But lets see if that actually works

**Comment by davsclaus** [comment]
add to whitelist

**Comment by oscerd** [comment]
@davsclaus Thank you very much.

I hope to do something more: actually I'm doing dependencies update and just some work on fabric8 maven plugin. Hopefully I'll go deep into the code and I'll be able to contributing more meaningfully.

**Comment by davsclaus** [comment]
@oscerd all work is important. You do great, and a great way to start. If you dive direct into the mysterious world of kubernetes and its kubenetes.json and whatnot you may get lost. 

Though we should / may get back on focus on jube to make that better - its mostly Java stuff and therefore more familiar land. It needs some work to upgrade to hawtio v2 and match kubernetes 1.0

**Pull request merged**
